// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByblRqm2Yj6I4nNUhUuYGTH64-nq2MHh8',
    appId: '1:678118629589:web:912984355ff264e224c25c',
    messagingSenderId: '678118629589',
    projectId: 'graduation-babb7',
    authDomain: 'graduation-babb7.firebaseapp.com',
    storageBucket: 'graduation-babb7.appspot.com',
    measurementId: 'G-F1T985KD3W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjofevtVe3j2TsAYp_Uy9Pg3Nzrv11fbA',
    appId: '1:678118629589:android:577a6f1841f92de824c25c',
    messagingSenderId: '678118629589',
    projectId: 'graduation-babb7',
    storageBucket: 'graduation-babb7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRTZdTNQ6y5aJeM45vdGbTgwn9w_GAMSs',
    appId: '1:678118629589:ios:2e558c4dc52bf99e24c25c',
    messagingSenderId: '678118629589',
    projectId: 'graduation-babb7',
    storageBucket: 'graduation-babb7.appspot.com',
    iosClientId: '678118629589-9pueb5as0uv9ae7u30frh82uhv6232i2.apps.googleusercontent.com',
    iosBundleId: 'com.example.graduation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRTZdTNQ6y5aJeM45vdGbTgwn9w_GAMSs',
    appId: '1:678118629589:ios:2e558c4dc52bf99e24c25c',
    messagingSenderId: '678118629589',
    projectId: 'graduation-babb7',
    storageBucket: 'graduation-babb7.appspot.com',
    iosClientId: '678118629589-9pueb5as0uv9ae7u30frh82uhv6232i2.apps.googleusercontent.com',
    iosBundleId: 'com.example.graduation',
  );
}
